package com.example.boxdataupdate

/**
 * JSON config
 */
val jsonConfig =
    "{" +
            "   \"minutes_per_interval\":120," +
            "   \"intervals\":[" +
            "      {" +
            "         \"serial_initial\":0," +
            "         \"serial_final\":8," +
            "         \"hour_initial\":\"00:00:00\"," +
            "         \"hour_final\":\"01:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":9," +
            "         \"serial_final\":16," +
            "         \"hour_initial\":\"02:00:00\"," +
            "         \"hour_final\":\"03:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":17," +
            "         \"serial_final\":24," +
            "         \"hour_initial\":\"04:00:00\"," +
            "         \"hour_final\":\"05:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":25," +
            "         \"serial_final\":33," +
            "         \"hour_initial\":\"06:00:00\"," +
            "         \"hour_final\":\"07:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":34," +
            "         \"serial_final\":41," +
            "         \"hour_initial\":\"08:00:00\"," +
            "         \"hour_final\":\"09:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":42," +
            "         \"serial_final\":49," +
            "         \"hour_initial\":\"10:00:00\"," +
            "         \"hour_final\":\"11:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":50," +
            "         \"serial_final\":58," +
            "         \"hour_initial\":\"12:00:00\"," +
            "         \"hour_final\":\"13:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":59," +
            "         \"serial_final\":66," +
            "         \"hour_initial\":\"14:00:00\"," +
            "         \"hour_final\":\"15:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":67," +
            "         \"serial_final\":74," +
            "         \"hour_initial\":\"16:00:00\"," +
            "         \"hour_final\":\"17:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":75," +
            "         \"serial_final\":83," +
            "         \"hour_initial\":\"18:00:00\"," +
            "         \"hour_final\":\"19:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":84," +
            "         \"serial_final\":91," +
            "         \"hour_initial\":\"20:00:00\"," +
            "         \"hour_final\":\"21:59:59\"" +
            "      }," +
            "      {" +
            "         \"serial_initial\":92," +
            "         \"serial_final\":99," +
            "         \"hour_initial\":\"22:00:00\"," +
            "         \"hour_final\":\"23:59:59\"" +
            "      }" +
            "   ]" +
            "}"